public enum TokenType {
    // Keywords
    INT, FLOAT, CHAR, IF, ELSE, WHILE, RETURN, PRINT, INPUT, VAR, FUN, FOR, DO, SWITCH, CASE, DEFAULT, BREAK, CONTINUE, CLASS, NEW, THIS, SUPER, TRUE, FALSE, NULL,

    // Literals
    IDENTIFIER, NUMBER, CHAR_LITERAL, STRING_LITERAL, BOOLEAN_LITERAL, NULL_LITERAL,

    // Operators
    PLUS, MINUS, MULTIPLY, DIVIDE, MODULO, 
    ASSIGN, // "="
    EQUAL, NOT_EQUAL, LESS, GREATER, LESS_EQUAL, GREATER_EQUAL, // "==", "!=", "<", ">", "<=", ">="
    AND, OR, NOT, // "&&", "||", "!"
    INCREMENT, DECREMENT, // "++", "--"
    PLUS_EQUAL, MINUS_EQUAL, MULTIPLY_EQUAL, DIVIDE_EQUAL, MODULO_EQUAL, // "+=", "-=", "*=", "/=", "%="

    // Punctuation
    SEMICOLON, COMMA, LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, LEFT_BRACKET, RIGHT_BRACKET, COLON,

    // Special
    EOF // End of File
}